# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Oracle.JDK.18
PackageVersion: 18.0.1.1
PackageLocale: en-US
Publisher: Oracle Corporation
PackageName: Java SE Development Kit 18
License: Copyright (c) Oracle
ShortDescription: The JDK is a development environment for building applications and components using the Java programming language.
ManifestType: defaultLocale
ManifestVersion: 1.1.0

